### PR TITLE
Update to e-g 0.8 and remove nodejs dependency

### PR DESCRIPTION
**Pull request by spookyvision**
This PR updates the simulator to the current version of `embedded-graphics`, 0.8. It also replaces the examples' nodejs based development server / build process approach with [cargo-run-wasm](https://github.com/rukai/cargo-run-wasm), making them far more self-contained. One downside is that custom `index.html` templates cannot be supplied this way, but that's not a huge issue since [trunk](https://trunkrs.dev/) exists. But requiring `trunk` would have swapped one dependency out for another, hence the `run-wasm` approach.

### CODE REVIEW

**Comment by pferreir** [comment]
It would be nice to see this one merged!

**Comment by spookyvision** [comment]
oh, true

**Comment by rahul-thakoor** [comment]
cool, thanks @spookyvision 

could you please bump the version and squash the commits into one?

**Comment by spookyvision** [comment]
@rahul-thakoor unfortunately I rebased too hard, so there's now an additional merge commit I'm not sure I'll be able to squash. Hope that's ok.

**Pull request merged**
